use std::fmt::Display;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Instruction {
    Noop,
    LoadBCFrom16Imm { new_value: u16 },
    IncrementBC,
    DecrementB,
    LoadBFrom8Imm { new_value: u8 },
    DecrementC,
    LoadCFrom8Imm { new_value: u8 },
    LoadDEFrom16Imm { new_value: u16 },
    StoreAAtDE,
    IncrementDE,
    IncrementD,
    JumpRelative { offset: i8 },
    LoadAFromDE,
    IncrementE,
    JumpRelativeIfNotZero { offset: i8 },
    LoadHLFrom16Imm { new_value: u16 },
    StoreAAtHLAndIncrement,
    IncrementHL,
    IncrementH,
    LoadHFrom8Imm { new_value: u8 },
    JumpRelativeIfZero { offset: i8 },
    LoadAFromHLAndInc,
    IncrementL,
    DecrementL,
    LoadSPFrom16Imm { new_value: u16 },
    StoreAAtHLAndDecrement,
    LoadAFrom8Imm { new_value: u8 },
    LoadBFromHL,
    LoadBFromA,
    LoadCFromL,
    LoadCFromHL,
    LoadDFromHL,
    LoadHFromL,
    StoreAAtHL,
    LoadAFromB,
    LoadAFromH,
    LoadAFromL,
    XorCWithA,
    XorHLWithA,
    OrCWithA,
    OrAWithA,
    PopBC,
    Jump { address: u16 },
    CallIfNotZero { address: u16 },
    PushBC,
    AddAWith8Imm { value: u8 },
    Return,
    Call { address: u16 },
    PushDE,
    SubtractAWith8Imm { value: u8 },
    OutputAToPort { address: u8 },
    PopHL,
    PushHL,
    AndAWith8Imm { value: u8 },
    StoreAAt16Imm { address: u16 },
    LoadAFromPort { address: u8 },
    LoadAFrom16Imm { address: u16 },
    PopAF,
    DisableInterrupts,
    PushAF,
    CompareAWith8Imm { value: u8 },
}

impl Instruction {
    pub fn size(&self) -> u16 {
        match self {
            Instruction::Noop => 1,
            Instruction::LoadBCFrom16Imm { .. } => 3,
            Instruction::IncrementBC => 1,
            Instruction::DecrementB => 1,
            Instruction::LoadBFrom8Imm { .. } => 2,
            Instruction::DecrementC => 1,
            Instruction::LoadCFrom8Imm { .. } => 2,
            Instruction::LoadDEFrom16Imm { .. } => 3,
            Instruction::StoreAAtDE => 1,
            Instruction::IncrementDE => 1,
            Instruction::IncrementD => 1,
            Instruction::JumpRelative { .. } => 2,
            Instruction::LoadAFromDE => 1,
            Instruction::IncrementE => 1,
            Instruction::JumpRelativeIfNotZero { .. } => 2,
            Instruction::LoadHLFrom16Imm { .. } => 3,
            Instruction::StoreAAtHLAndIncrement => 1,
            Instruction::IncrementHL => 1,
            Instruction::IncrementH => 1,
            Instruction::LoadHFrom8Imm { .. } => 2,
            Instruction::JumpRelativeIfZero { .. } => 2,
            Instruction::LoadAFromHLAndInc => 1,
            Instruction::IncrementL => 1,
            Instruction::DecrementL => 1,
            Instruction::LoadSPFrom16Imm { .. } => 3,
            Instruction::StoreAAtHLAndDecrement => 1,
            Instruction::LoadAFrom8Imm { .. } => 2,
            Instruction::LoadBFromHL => 1,
            Instruction::LoadBFromA => 1,
            Instruction::LoadCFromL => 1,
            Instruction::LoadCFromHL => 1,
            Instruction::LoadDFromHL => 1,
            Instruction::LoadHFromL => 1,
            Instruction::StoreAAtHL => 1,
            Instruction::LoadAFromB => 1,
            Instruction::LoadAFromH => 1,
            Instruction::LoadAFromL => 1,
            Instruction::XorCWithA => 1,
            Instruction::XorHLWithA => 1,
            Instruction::OrCWithA => 1,
            Instruction::OrAWithA => 1,
            Instruction::PopBC => 1,
            Instruction::Jump { .. } => 3,
            Instruction::CallIfNotZero { .. } => 3,
            Instruction::PushBC => 1,
            Instruction::AddAWith8Imm { .. } => 2,
            Instruction::Return => 1,
            Instruction::Call { .. } => 3,
            Instruction::PushDE => 1,
            Instruction::SubtractAWith8Imm { .. } => 2,
            Instruction::OutputAToPort { .. } => 2,
            Instruction::PopHL => 1,
            Instruction::PushHL => 1,
            Instruction::AndAWith8Imm { .. } => 2,
            Instruction::StoreAAt16Imm { .. } => 3,
            Instruction::LoadAFromPort { .. } => 2,
            Instruction::LoadAFrom16Imm { .. } => 3,
            Instruction::PopAF => 1,
            Instruction::DisableInterrupts => 1,
            Instruction::PushAF => 1,
            Instruction::CompareAWith8Imm { .. } => 2,
        }
    }
}

impl Display for Instruction {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str = match self {
            Instruction::Noop => format!("NOP"),
            Instruction::LoadBCFrom16Imm { new_value } => format!("LD BC, ${new_value:04X}"),
            Instruction::IncrementBC => format!("INC BC"),
            Instruction::DecrementB => format!("DEC B"),
            Instruction::LoadBFrom8Imm { new_value } => format!("LD B, ${new_value:02X}"),
            Instruction::DecrementC => format!("DEC C"),
            Instruction::LoadCFrom8Imm { new_value } => format!("LD C, ${new_value:02X}"),
            Instruction::LoadDEFrom16Imm { new_value } => format!("LD DE, ${new_value:04X}"),
            Instruction::StoreAAtDE => format!("LD (DE), A"),
            Instruction::IncrementDE => format!("INC DE"),
            Instruction::IncrementD => format!("INC D"),
            Instruction::JumpRelative { offset } => format!(
                "JR {sign}{mag:#X}",
                sign = if offset.is_negative() { '-' } else { '+' },
                mag = offset.abs()
            ),
            Instruction::LoadAFromDE => format!("LD A, (DE)"),
            Instruction::IncrementE => format!("INC E"),
            Instruction::JumpRelativeIfNotZero { offset } => format!(
                "JR NZ, {sign}{mag:#X}",
                sign = if offset.is_negative() { '-' } else { '+' },
                mag = offset.abs()
            ),
            Instruction::LoadHLFrom16Imm { new_value } => format!("LD HL, ${new_value:04X}"),
            Instruction::StoreAAtHLAndIncrement => format!("LD (HL+), A"),
            Instruction::IncrementHL => format!("INC HL"),
            Instruction::IncrementH => format!("INC H"),
            Instruction::LoadHFrom8Imm { new_value } => format!("LD H, ${new_value:02X}"),
            Instruction::JumpRelativeIfZero { offset } => format!(
                "JR Z, {sign}{mag:#X}",
                sign = if offset.is_negative() { '-' } else { '+' },
                mag = offset.abs()
            ),
            Instruction::LoadAFromHLAndInc => format!("LD A, (HL+)"),
            Instruction::IncrementL => format!("INC L"),
            Instruction::DecrementL => format!("DEC L"),
            Instruction::LoadSPFrom16Imm { new_value } => format!("LD SP, ${new_value:04X}"),
            Instruction::StoreAAtHLAndDecrement => format!("LD (HL-), A"),
            Instruction::LoadAFrom8Imm { new_value } => format!("LD A, ${new_value:02X}"),
            Instruction::LoadBFromHL => format!("LD B, (HL)"),
            Instruction::LoadBFromA => format!("LD B, A"),
            Instruction::LoadCFromL => format!("LD C, L"),
            Instruction::LoadCFromHL => format!("LD C, (HL)"),
            Instruction::LoadDFromHL => format!("LD D, (HL)"),
            Instruction::LoadHFromL => format!("LD H, L"),
            Instruction::StoreAAtHL => format!("LD (HL), A"),
            Instruction::LoadAFromB => format!("LD A, B"),
            Instruction::LoadAFromH => format!("LD A, H"),
            Instruction::LoadAFromL => format!("LD A, L"),
            Instruction::XorCWithA => format!("XOR C"),
            Instruction::XorHLWithA => format!("XOR (HL)"),
            Instruction::OrCWithA => format!("OR C"),
            Instruction::OrAWithA => format!("OR A"),
            Instruction::PopBC => format!("POP BC"),
            Instruction::Jump { address } => format!("JP ${address:04X}"),
            Instruction::CallIfNotZero { address } => format!("CALL NZ, ${address:04X}"),
            Instruction::PushBC => format!("PUSH BC"),
            Instruction::AddAWith8Imm { value } => format!("ADD A, ${value:02X}"),
            Instruction::Return => format!("RET"),
            Instruction::Call { address } => format!("CALL ${address:04X}"),
            Instruction::PushDE => format!("PUSH DE"),
            Instruction::SubtractAWith8Imm { value } => format!("SUB A, ${value:02X}"),
            Instruction::OutputAToPort { address } => format!("LD ${address:02X}, A"),
            Instruction::PopHL => format!("POP HL"),
            Instruction::PushHL => format!("PUSH HL"),
            Instruction::AndAWith8Imm { value } => format!("AND ${value:02X}"),
            Instruction::StoreAAt16Imm { address } => format!("LD ${address:04X}, A"),
            Instruction::LoadAFromPort { address } => format!("LD A, ${address:02X}"),
            Instruction::LoadAFrom16Imm { address } => format!("LD A, ${address:04X}"),
            Instruction::PopAF => format!("POP AF"),
            Instruction::DisableInterrupts => format!("DI"),
            Instruction::PushAF => format!("PUSH AF"),
            Instruction::CompareAWith8Imm { value } => format!("CP ${value:02X}"),
        };
        write!(f, "{str}")
    }
}
